import { Geist, Geist_Mono, Roboto, Shadows_Into_Light } from "next/font/google";
import "./globals.css";
import { AuthModalProvider } from "../components/context/AuthModalContext";
import AuthModalHost from "../components/AuthModalHost";
import { AuthModalWatcher } from "@/components/auth/AuthModalWatcher";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

const shadows = Shadows_Into_Light({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-shadows",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${shadows.variable} antialiased pageColor`}
      >
        <AuthModalProvider>
          <AuthModalHost />          
          {children}         
          <AuthModalWatcher /> 
        </AuthModalProvider>
         
        
      </body>
    </html>
  );
}
